rna <- readRDS("30k_snRNA.RDS")
atac <- readRDS("9k_snATAC.RDS")
genes <- rownames(rna)
diagnosis <- levels(dataset@meta.data[["diagnosis"]])
metadata_rna <- data.table::setDT(rna[[]])
metadata_atac <- data.table::setDT(atac[[]])
mtheme <- bs_theme(version = 5, bootswatch = "materia")

umap_rna <- data.table::setDT(Seurat::Embeddings(rna, reduction = "umap"))
umap_atac <- data.table::setDT(Seurat::Embeddings(atac, reduction = "umap"))
